input_records:
  1:
    label: c1.b1.t1
  2:
    label: c1.b1.t2
  3:
    label: c1.b2.t1
  4:
    label: c1.b2.t2
  5:
    label: c2.b1.t1
  6:
    label: c2.b1.t2
  7:
    label: c2.b2.t1
  8:
    label: c2.b2.t2

merge_before_dedup_records:
  9:
    merge_from: [1, 2]
    label: c1.b1
  10:
    merge_from: [3, 4]
    label: c1.b2
  11:
    merge_from: [5, 6]
    label: c2.b1
  12:
    merge_from: [7, 8]
    label: c2.b2

merge_after_dedup_records:
  13:
    merge_from: [9, 10]
    label: c1
  14:
    merge_from: [11, 12]
    label: c1

M129:
  assembly: M129
  aligner: bwa
  aligner_index_dir: tests/assets/index/bwa/
  aligner_index_prefix: M129
  fastq: ["tests/assets/fastq/1k/1k_ERR1413593_1.fq.gz", "tests/assets/fastq/1k/1k_ERR1413593_2.fq.gz"]

standard_alignment:
  config_fastq_align:
    cmd_align:
      base_command: ${aligner} mem
      flags: ["-S", "-P", "-5", "-M", "-p"]
      opts:
        '-t': '${cpus}'
      args: [
        "${aligner_index_dir}/${aligner_index_prefix}",
        "${fastq1}",
        "${fastq2}"
      ]
    cmd_samtools_view:
      base_command: "samtools view"
      flags: ["-b"]
      opts:
        '-o': '${bam}'

methyl_alignment:
  config_fastq_align:
    cmd_align:
      base_command: python -m ${aligner}
      flags: ["--do-not-penalize-chimeras", "-p"]
      opts:
        '--reference': '${aligner_index_dir}/${aligner_index_prefix}'
        '-t': '${cpus}'
      args: ["${fastq1}", "${fastq2}"]
    base_command: "samtools view"
    flags: ["-b"]
    opts:
      '-o': '${bam}'


